uikit_components.settings:
  type: config_object
  label: 'UIkit Components'
  mapping:
    uikit_components:
      type: mapping
      mapping:
        uikit_framework_version:
          type: select
          label: 'UIkit Framework'

uikit_components.core:
  type: config_object
  label: 'Core components'
  mapping:
    uikit_components:
      type: mapping
      mapping:

uikit_components.advanced:
  type: config_object
  label: 'Advanced components'
  mapping:
    uikit_components:
      type: mapping
      mapping:
