uikit_components.settings:
  type: mapping
  label: 'UIkit Components'
  mapping:
    uikit_framework_version:
      type: string
      label: 'UIkit Framework'

uikit_components.core:
  type: config_object
  label: 'Core components'
  mapping:
    uikit_components:
      type: mapping
      mapping:

uikit_components.advanced:
  type: config_object
  label: 'Advanced components'
  mapping:
    uikit_components:
      type: mapping
      mapping:

block.settings.*.third_party.uikit_components:
  mapping:
    uikit_navbar_alignment:
      type: integer
      label: 'UIkit navbar alignment'
